name: 'Validate Unity Tests.'
description: 'A GitHub Action code coverage quality gate for Unity Code Coverage tools.'
inputs:
  coverage-file-path:
    description: 'The path of the coverage file to parse.'
    required: true
    default: './artifacts/CodeCoverage/Report/Summary.xml'
  required-coverage:  
    description: 'Percentage of code coverage under which quality gate will fail.'
    required: true
    default: '75'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.required-coverage }} ${{ inputs.coverage-file-path }}